[openshift] Fix "unable to decode" error
Full error message:
error: unable to decode "template.yaml": [pos 4709]:
json: expect char '"' but got char '1'